project:
  type: website
  output-dir: "."

website:
  title: "YOUR NAME"
  navbar:
    # background: "#006600"
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2024"

format:
  html:
    theme: 
      light: united
      dark: vapor
    mainfont: system-ui; 
    highlight-style: espresso  # atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html

