project:
  type: website
  output-dir: "."

website:
  title: "YOUR NAME"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    include-after-body: target_blank.html

